force-app/main/default/objects/GCAI_Prompt_Template__c/GCAI_Prompt_Template__c.object-meta.xml
<CustomObject>
    <description>AI Prompt template object store library of templates</description>
    <label>Prompt Template</label>
    <nameField>
        <label>Sample Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <description>Type of actions expected from prompt to generate</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyze</fullName>
            </value>
            <value>
                <fullName>Answer</fullName>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Summarize</fullName>
            </value>
            <value>
                <fullName>Refine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>Input types</description>
    <label>Input</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/IsSelected__c.field-meta.xml
<CustomField>
    <fullName>IsSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Model field used in UI component logic</description>
    <label>IsSelected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Sample_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Sample_Prompt__c</fullName>
    <description>Store example prompt</description>
    <label>Sample Prompt</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GCAI_PromptTemplateCtrlTest.cls
/*
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 * @Author: igor.androsov 
 * @Date: 2023-12-09 16:10:37 
 * @Last Modified by: igor.androsov
 * @Last Modified time: 2023-12-09 16:51:41
 */

 @isTest
 public class GCAI_PromptTemplateCtrlTest {
     @isTest
     static void testGetTemplates() {
         // Create test data
         GCAI_Prompt_Template__c template = new GCAI_Prompt_Template__c();
         template.Name = 'Test Template';
         template.Sample_Prompt__c = 'Craetae executive summmary text';
         template.Language__c = 'EN';
         template.Input__c = 'Some input text';
         template.Role__c = 'Developer';
         template.Action_Type__c = 'Create';
         template.IsSelected__c = true;
         insert template;
 
         // Call the method to test
         List<GCAI_Prompt_Template__c> templates = GCAI_PromptTemplateCtrl.getTemplates();
 
         // Assert the result
         System.assertEquals(1, templates.size(), 'Expected 1 prompt template');
         System.assertEquals('Test Template', templates[0].Name, 'Temaplte name did not match');
         System.assertEquals('Craetae executive summmary text', templates[0].Sample_Prompt__c, 'Invalid prompt');
     }
 }
 