force-app/main/default/objects/GCAI_Prompt_Template__c/GCAI_Prompt_Template__c.object-meta.xml
<CustomObject>
    <description>AI Prompt template object store library of templates</description>
    <label>Prompt Template</label>
    <nameField>
        <label>Sample Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <description>Type of actions expected from prompt to generate</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyze</fullName>
            </value>
            <value>
                <fullName>Answer</fullName>
            </value>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Summarize</fullName>
            </value>
            <value>
                <fullName>Refine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>Input types</description>
    <label>Input</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/IsSelected__c.field-meta.xml
<CustomField>
    <fullName>IsSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Model field used in UI component logic</description>
    <label>IsSelected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GCAI_Prompt_Template__c/fields/Sample_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Sample_Prompt__c</fullName>
    <description>Store example prompt</description>
    <label>Sample Prompt</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GCAI_PromptTemplateSelector.cls
/*
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 * 
 */
public with sharing class GCAI_PromptTemplateSelector {
    
    public static List<GCAI_Prompt_Template__c> getTemplates(){
        return [SELECT Id, Name, Action_Type__c, Input__c, IsSelected__c, Language__c, Role__c, Sample_Prompt__c 
                FROM GCAI_Prompt_Template__c WITH SECURITY_ENFORCED];
    }
}